#!/usr/bin/env bash

sleep=5
alive_interval=10
attempts=100
ssh_opts="-Y -oCompression=yes -oServerAliveInterval=$alive_interval"

host="${1?Missing host argument}"
session="${2:-ssh}"
tmux_cmd="tmux attach -t $session || tmux new -s $session"

i=0
while [ $i -lt $attempts ]; do
  ssh -t "$host" $ssh_opts "$tmux_cmd"
  if [ $? -eq 0 ]; then break; fi
  echo "SSH connection lost ($i/$attempts), reconnecting in $sleep seconds..."
  sleep $sleep
  i=$((i + 1))
done

echo "SSH max reconnection attempts reached: $attempts. Stopping..."
date
