#!/bin/bash

# Wrapper function for Maven's mvn command.
mvn-color() {
    if [[ $* == *--no-color* ]]; then
        mvn $(echo $@ | sed "s/ --no-color//")
        return $?
    fi
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && echo $PWD )"
    source "$DIR/lib/terminal_colors.sh"
    declare -r INFO_STYLE="${FORMAT_BOLD}${COLOR_BLUE}"
    declare -r WARN_STYLE="${FORMAT_BOLD}${COLOR_YELLOW}"
    declare -r ERR_STYLE="${FORMAT_BOLD}${COLOR_RED}"
    declare -r SUCCESS_STYLE="${FORMAT_BOLD}${COLOR_GREEN}"
    declare -r FAILURE_STYLE="${FORMAT_BOLD}${COLOR_RED}"
    # Filter mvn output using sed
    unset LANG
    LC_CTYPE=C mvn "$@" | sed \
        -e "s/\(^\[WARNING\]\)\(.*\)/${WARN_STYLE}\1${FORMAT_RESET}\2/g" \
        -e "s/\(^\[ERROR\]\)\(.*\)/${ERR_STYLE}\1${FORMAT_RESET}\2/g" \
        -e "s/\(\-\{3,\}\)/${INFO_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/\(T E S T S\)/${INFO_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/\(^\[INFO\]\ Building .*\)/${INFO_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/\(^\[INFO\]\ \)\(BUILD \(SUCCESS\|SUCCESSFUL\)\)/${INFO_STYLE}\1${SUCCESS_STYLE}\2${FORMAT_RESET}/g" \
        -e "s/\(^\[INFO\]\ \)\(BUILD FAILURE\)/${INFO_STYLE}\1${FAILURE_STYLE}\2${FORMAT_RESET}/g" \
        -e "s/\(^\[INFO\]\)/${INFO_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/\(FAILURE\)/${FAILURE_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/\(SUCCESS\)/${SUCCESS_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/\(SKIPPED\)/${WARN_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/\(<<< FAILURE!\)/${ERR_STYLE}\1${FORMAT_RESET}/g" \
        -e "s/^Tests run: \([^,]*\), Failures: \([^,]*\), Errors: \([^,]*\), Skipped: \([^,]*\)/${SUCCESS_STYLE}Tests run: \1${FORMAT_RESET}, Failures: ${ERR_STYLE}\2${FORMAT_RESET}, Errors: ${ERR_STYLE}\3${FORMAT_RESET}, Skipped: ${WARN_STYLE}\4${FORMAT_RESET}/g"
    local MVN_EXIT=${PIPESTATUS[0]}
    # Make sure formatting is reset
    echo -ne ${FORMAT_RESET}
    return $MVN_EXIT;
}

if [ "$0" = "$BASH_SOURCE" ]; then
    # Scipt is executed directly
    mvn-color "$@"
fi
